# Generated by Django 6.0.6 on 2026-07-07 11:23

from django.db import migrations


def populate_rbac_data(apps, schema_editor):
    Role = apps.get_model("attendance", "Role")
    Section = apps.get_model("attendance", "Section")
    Permission = apps.get_model("attendance", "Permission")
    RolePermission = apps.get_model("attendance", "RolePermission")
    UserProfile = apps.get_model("attendance", "UserProfile")

    # 1. Define and Create Permissions
    permissions_data = [
        # Dashboard
        ("View Dashboard", "dashboard.view", "dashboard", "View standard dashboard metrics"),
        ("Admin Dashboard", "dashboard.admin", "dashboard", "Access full organization dashboard metrics"),
        # Attendance
        ("View Own Attendance", "attendance.view_own", "attendance", "View own attendance logs"),
        ("View Section Attendance", "attendance.view_section", "attendance", "View attendance of section employees"),
        ("View All Attendance", "attendance.view_all", "attendance", "View attendance logs of all employees"),
        ("Export Attendance", "attendance.export", "attendance", "Export attendance logs to file"),
        ("Edit Attendance", "attendance.edit", "attendance", "Create/Modify attendance records"),
        ("Delete Attendance", "attendance.delete", "attendance", "Delete attendance records"),
        # Leave
        ("View Leaves", "leave.view", "leave", "View leave requests"),
        ("Create Leave Request", "leave.create", "leave", "Create new leave requests"),
        ("Approve Leave Request", "leave.approve", "leave", "Approve pending leave requests"),
        ("Reject Leave Request", "leave.reject", "leave", "Reject pending leave requests"),
        # Overtime
        ("View Overtime", "ot.view", "ot", "View overtime metrics and requests"),
        ("Edit Overtime", "ot.edit", "ot", "Modify overtime records/requests"),
        ("Approve Overtime", "ot.approve", "ot", "Approve overtime requests"),
        # Employee
        ("View Employees", "employee.view", "employee", "View employee profiles"),
        ("Create Employee", "employee.create", "employee", "Add new employee profile"),
        ("Edit Employee", "employee.edit", "employee", "Modify employee profiles"),
        ("Delete Employee", "employee.delete", "employee", "Delete employee profiles"),
        # Administration
        ("Manage Roles", "role.manage", "administration", "Create, edit and manage RBAC roles"),
        ("Manage Sections", "section.manage", "administration", "Create, edit and manage sections"),
        ("Manage Permissions", "permission.manage", "administration", "Manage system permissions"),
        ("Manage Users", "user.manage", "administration", "View and edit user profiles and credentials"),
        # Reports
        ("View Reports", "report.view", "reports", "Access system reporting"),
        ("Export Excel Report", "report.export_excel", "reports", "Download reports in Excel format"),
        ("Export PDF Report", "report.export_pdf", "reports", "Download reports in PDF format"),
        # System
        ("View Audit Logs", "audit.view", "system", "View system audit logs"),
        ("Manage Settings", "settings.manage", "system", "Modify global system settings"),
    ]

    perms_by_code = {}
    for name, code, module, desc in permissions_data:
        perm, _ = Permission.objects.get_or_create(
            code=code,
            defaults={"name": name, "module": module, "description": desc},
        )
        perms_by_code[code] = perm

    # 2. Define and Create Roles
    roles_data = [
        ("Employee", "employee", "Standard employee role with access to own data.", "OWN"),
        ("SMT PD", "smt_pd", "SMT Production Director with access to assigned section.", "SECTION"),
        ("ASSY PD", "assy_pd", "Assembly Production Director with access to assigned section.", "SECTION"),
        ("Admin", "admin", "System Administrator with full access.", "ALL"),
        ("Supervisor", "supervisor", "Section level supervisor.", "SECTION"),
        ("HR Manager", "hr_manager", "HR Manager with full organization scope.", "ALL"),
    ]

    roles_by_code = {}
    for name, code, desc, scope in roles_data:
        role, _ = Role.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": desc, "data_scope": scope},
        )
        roles_by_code[code] = role

    # 3. Assign Permissions to Roles
    # Admin & HR get all
    all_perms = Permission.objects.all()
    for perm in all_perms:
        RolePermission.objects.get_or_create(role=roles_by_code["admin"], permission=perm)
        RolePermission.objects.get_or_create(role=roles_by_code["hr_manager"], permission=perm)

    # Employee Permissions
    employee_perms = ["dashboard.view", "attendance.view_own", "leave.view", "leave.create", "ot.view"]
    for code in employee_perms:
        if code in perms_by_code:
            RolePermission.objects.get_or_create(
                role=roles_by_code["employee"], permission=perms_by_code[code]
            )

    # Section-level Roles Permissions
    section_perms = [
        "dashboard.view",
        "attendance.view_own",
        "attendance.view_section",
        "attendance.export",
        "leave.view",
        "leave.create",
        "leave.approve",
        "leave.reject",
        "ot.view",
        "ot.edit",
        "ot.approve",
        "employee.view",
    ]
    for code in section_perms:
        if code in perms_by_code:
            RolePermission.objects.get_or_create(
                role=roles_by_code["smt_pd"], permission=perms_by_code[code]
            )
            RolePermission.objects.get_or_create(
                role=roles_by_code["assy_pd"], permission=perms_by_code[code]
            )
            RolePermission.objects.get_or_create(
                role=roles_by_code["supervisor"], permission=perms_by_code[code]
            )

    # 4. Create Sections
    sections_data = [
        ("Sector 63 - SMT PD", "s63_smt", "Sector 63 - SMT PD Department", "Sector 63"),
        ("Phase 2 - SMT PD", "c39_smt", "Phase 2 - SMT PD Department", "C39"),
        ("Sector 63 - ASSY PD", "s63_assy", "Sector 63 - ASSY PD Department", "Sector 63"),
        ("Phase 2 - ASSY PD", "c39_assy", "Phase 2 - ASSY PD Department", "C39"),
        ("Phase 2 - Marketing", "p2_mkt", "Phase 2 - Marketing Department", "C39"),
        ("Sector 63 - Marketing", "s63_mkt", "Sector 63 - Marketing Department", "Sector 63"),
    ]

    sections_by_code = {}
    for name, code, desc, loc in sections_data:
        sec, _ = Section.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": desc, "location": loc},
        )
        sections_by_code[code] = sec

    # 5. Migrate Existing UserProfiles
    for profile in UserProfile.objects.all():
        old_role = profile.role
        old_section = profile.section
        username = profile.user.username.upper()

        # Determine the role
        new_role = roles_by_code["employee"]  # Default
        new_section = None

        # Check special usernames first
        if username == "SMT_PD_C39":
            new_role = roles_by_code["smt_pd"]
            new_section = sections_by_code["c39_smt"]
        elif username == "SMT_PD_S63":
            new_role = roles_by_code["smt_pd"]
            new_section = sections_by_code["s63_smt"]
        elif username in ("ASSBLY_PD_C39", "ASSY_PD_C39"):
            new_role = roles_by_code["assy_pd"]
            new_section = sections_by_code["c39_assy"]
        elif username in ("ASSBLY_PD_S63", "ASSY_PD_S63"):
            new_role = roles_by_code["assy_pd"]
            new_section = sections_by_code["s63_assy"]
        elif username == "19105540":
            new_role = roles_by_code["employee"]
            new_section = sections_by_code["p2_mkt"]
        elif username == "19105639":
            new_role = roles_by_code["employee"]
            new_section = sections_by_code["s63_mkt"]
        elif profile.user.is_superuser:
            new_role = roles_by_code["admin"]
        else:
            # Check by old fields
            if old_role == "smt_pd":
                new_role = roles_by_code["smt_pd"]
                if old_section == "s63":
                    new_section = sections_by_code["s63_smt"]
                elif old_section == "c39":
                    new_section = sections_by_code["c39_smt"]
            elif old_role == "assy_pd":
                new_role = roles_by_code["assy_pd"]
                if old_section == "s63":
                    new_section = sections_by_code["s63_assy"]
                elif old_section == "c39":
                    new_section = sections_by_code["c39_assy"]
            else:
                new_role = roles_by_code["employee"]

        profile.role_fk = new_role
        profile.section_fk = new_section
        profile.save()


def reverse_rbac_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_permission_role_userprofile_role_fk_section_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_rbac_data, reverse_rbac_data),
    ]
