# Generated by Django 6.0.6 on 2026-07-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20260707_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="section",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="role_fk",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="section_fk",
            new_name="section",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="attendance.role",
            ),
        ),
    ]
