# Generated by Django 6.0.6 on 2026-07-07 12:01

from django.db import migrations


def migrate_to_enterprise_hierarchy(apps, schema_editor):
    Company = apps.get_model("attendance", "Company")
    Plant = apps.get_model("attendance", "Plant")
    Department = apps.get_model("attendance", "Department")
    Section = apps.get_model("attendance", "Section")
    UserProfile = apps.get_model("attendance", "UserProfile")

    # 1. Create Company
    company, _ = Company.objects.get_or_create(
        code="ismartu",
        defaults={
            "name": "ISmartU",
            "description": "ISmartU Enterprise Org",
            "is_active": True,
        },
    )

    # 2. Create Plants
    plant_s63, _ = Plant.objects.get_or_create(
        code="s63",
        defaults={
            "company": company,
            "name": "Sector 63",
            "address": "Sector 63, Noida",
            "city": "Noida",
            "state": "Uttar Pradesh",
            "country": "India",
            "description": "Sector 63 Plant",
            "is_active": True,
        },
    )

    plant_c39, _ = Plant.objects.get_or_create(
        code="c39",
        defaults={
            "company": company,
            "name": "Phase 2",
            "address": "Phase 2, Noida",
            "city": "Noida",
            "state": "Uttar Pradesh",
            "country": "India",
            "description": "Phase 2 Plant",
            "is_active": True,
        },
    )

    # 3. Create Departments
    dept_prod_s63, _ = Department.objects.get_or_create(
        code="prod",
        defaults={
            "plant": plant_s63,
            "name": "Production",
            "description": "Production Department under Sector 63",
            "is_active": True,
        },
    )

    dept_prod_c39, _ = Department.objects.get_or_create(
        code="prod_c39",
        defaults={
            "plant": plant_c39,
            "name": "Production",
            "description": "Production Department under Phase 2",
            "is_active": True,
        },
    )

    dept_mkt_c39, _ = Department.objects.get_or_create(
        code="p2_mkt_dept",
        defaults={
            "plant": plant_c39,
            "name": "Marketing",
            "description": "Marketing Department under Phase 2",
            "is_active": True,
        },
    )

    dept_mkt_s63, _ = Department.objects.get_or_create(
        code="s63_mkt_dept",
        defaults={
            "plant": plant_s63,
            "name": "Marketing",
            "description": "Marketing Department under Sector 63",
            "is_active": True,
        },
    )

    # 4. Map Sections to Departments
    section_mappings = {
        "s63_smt": dept_prod_s63,
        "c39_smt": dept_prod_c39,
        "s63_assy": dept_prod_s63,
        "c39_assy": dept_prod_c39,
        "p2_mkt": dept_mkt_c39,
        "s63_mkt": dept_mkt_s63,
    }

    for sec_code, dept in section_mappings.items():
        try:
            sec = Section.objects.get(code=sec_code)
            sec.department = dept
            sec.save()
        except Section.DoesNotExist:
            pass

    # 5. Map existing UserProfiles to Company, Plant, Department
    for profile in UserProfile.objects.all():
        profile.company = company
        if profile.section and profile.section.department:
            profile.plant = profile.section.department.plant
            profile.department = profile.section.department
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_company_department_alter_role_data_scope_auditlog_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_to_enterprise_hierarchy),
    ]
