# Generated by Django 6.0.6 on 2026-07-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20260707_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(default='http://10.61.248.6', help_text='Base URL without port, e.g., http://10.61.248.6', max_length=255)),
                ('port', models.IntegerField(default=18010, help_text='Port number, e.g., 18010')),
            ],
            options={
                'verbose_name': 'Attendance API Configuration',
                'verbose_name_plural': 'Attendance API Configuration',
            },
        ),
    ]
