# Generated by Django 6.0.6 on 2026-07-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendanceapiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_low_limit', models.FloatField(default=52.0, help_text="Overtime hours below this limit are classified as 'Low'")),
                ('ot_medium_limit', models.FloatField(default=78.0, help_text="Overtime hours below this limit (and above low limit) are classified as 'Medium'. Above this are 'High'.")),
            ],
            options={
                'verbose_name': 'Overtime Limit Configuration',
                'verbose_name_plural': 'Overtime Limit Configuration',
            },
        ),
    ]
