# Generated by Django 6.0.6 on 2026-07-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_overtimelimitconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, verbose_name='Employee ID')),
                ('plant', models.CharField(choices=[('S63', 'Sector 63 (S63)'), ('C39', 'Phase 2 (C39)')], max_length=10, verbose_name='Plant')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-date'],
            },
        ),
    ]
