# Generated by Django 6.0.6 on 2026-07-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_unchanged', models.IntegerField(default=0)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sync_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50)),
                ('employee_name', models.CharField(blank=True, default='', max_length=150)),
                ('attendance_date', models.DateField(db_index=True)),
                ('in_time', models.CharField(blank=True, default='', max_length=10)),
                ('out_time', models.CharField(blank=True, default='', max_length=10)),
                ('working_hours', models.FloatField(blank=True, default=0.0, null=True)),
                ('card_punch_ot', models.FloatField(blank=True, default=0.0, null=True)),
                ('requested_ot', models.FloatField(blank=True, default=0.0, null=True)),
                ('weekend_ot', models.FloatField(blank=True, default=0.0, null=True)),
                ('holiday_ot', models.FloatField(blank=True, default=0.0, null=True)),
                ('ot4', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_ot_all', models.FloatField(blank=True, default=0.0, null=True)),
                ('req_overtime', models.FloatField(blank=True, default=0.0, null=True)),
                ('approved_ot', models.FloatField(blank=True, default=0.0, null=True)),
                ('wt_id', models.CharField(blank=True, default='', max_length=50)),
                ('wt_type_no', models.CharField(blank=True, default='', max_length=50)),
                ('attendance_source', models.CharField(blank=True, default='', max_length=100)),
                ('day', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('attendance_status', models.CharField(blank=True, default='', max_length=100)),
                ('shift', models.CharField(blank=True, default='', max_length=100)),
                ('mobile', models.CharField(blank=True, default='', max_length=50)),
                ('late_minutes', models.FloatField(blank=True, default=0.0, null=True)),
                ('leave_type', models.CharField(blank=True, default='', max_length=100)),
                ('workday', models.CharField(blank=True, default='', max_length=50)),
                ('weekday', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-attendance_date', 'employee_id'],
                'unique_together': {('employee_id', 'attendance_date')},
            },
        ),
    ]
