# Generated by Django 6.0.6 on 2026-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_synclog_attendancerecord'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance_date', 'employee_id'], name='attendance__attenda_7a97da_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendance_date', 'day'], name='attendance__attenda_c1c7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee_id', 'attendance_date'], name='attendance__employe_a000ce_idx'),
        ),
    ]
