# Generated by Django 6.0.7 on 2026-07-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_synclog_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='CorrectionRequest',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='OvertimeRequest',
        ),
    ]
