# Generated by Django 6.0.6 on 2026-07-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_leaverequest_user_remove_overtimerequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='work_time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
